services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - ./backend/db.env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf:ro
       - ./jam-app/dist/jam-app/browser:/usr/share/nginx/html
    depends_on:
      - backend
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: